name: "Workflow call"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  wf:
    uses: lindeskar/gha-test/.github/workflows/workflow.yml@main
    with:
      action-version: "a84b62ea892599a58fb8deb3bfebd0bdfca4685f"
